// Nikkei 225 Full Data
// Generated by Script
const marketData = {
    "name": "Nikkei 225",
    "children": [
        {
            "name": "電気機器",
            "children": [
                {
                    "name": "東京エレクトロン",
                    "code": "8035",
                    "marketCap": 120000,
                    "url": ""
                },
                {
                    "name": "ソフトバンクG",
                    "code": "9984",
                    "marketCap": 90000,
                    "url": ""
                },
                {
                    "name": "キーエンス",
                    "code": "6861",
                    "marketCap": 155000,
                    "url": ""
                },
                {
                    "name": "ソニーG",
                    "code": "6758",
                    "marketCap": 160000,
                    "url": "https://youtu.be/1tkleTadv1c"
                },
                {
                    "name": "村田製作所",
                    "code": "6981",
                    "marketCap": 55000,
                    "url": ""
                },
                {
                    "name": "日立製作所",
                    "code": "6501",
                    "marketCap": 110000,
                    "url": ""
                },
                {
                    "name": "富士通",
                    "code": "6702",
                    "marketCap": 40000,
                    "url": ""
                },
                {
                    "name": "パナソニック",
                    "code": "6752",
                    "marketCap": 38000,
                    "url": ""
                },
                {
                    "name": "オリンパス",
                    "code": "7733",
                    "marketCap": 30000,
                    "url": ""
                },
                {
                    "name": "キヤノン",
                    "code": "7751",
                    "marketCap": 45000,
                    "url": ""
                },
                {
                    "name": "ファナック",
                    "code": "6954",
                    "marketCap": 40000,
                    "url": ""
                },
                {
                    "name": "京セラ",
                    "code": "6971",
                    "marketCap": 25000,
                    "url": ""
                },
                {
                    "name": "エプソン",
                    "code": "6724",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "アルプスアルパイン",
                    "code": "6770",
                    "marketCap": 3000,
                    "url": ""
                },
                {
                    "name": "NEC",
                    "code": "6701",
                    "marketCap": 28000,
                    "url": ""
                },
                {
                    "name": "三菱電機",
                    "code": "6503",
                    "marketCap": 50000,
                    "url": ""
                },
                {
                    "name": "日東電工",
                    "code": "6988",
                    "marketCap": 15000,
                    "url": ""
                },
                {
                    "name": "富士電機",
                    "code": "6504",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "安川電機",
                    "code": "6506",
                    "marketCap": 14000,
                    "url": ""
                },
                {
                    "name": "ミネベアミツミ",
                    "code": "6479",
                    "marketCap": 11000,
                    "url": ""
                },
                {
                    "name": "SCREEN",
                    "code": "7735",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "レーザーテック",
                    "code": "6920",
                    "marketCap": 25000,
                    "url": ""
                },
                {
                    "name": "アドバンテスト",
                    "code": "6857",
                    "marketCap": 40000,
                    "url": ""
                },
                {
                    "name": "TDK",
                    "code": "6762",
                    "marketCap": 30000,
                    "url": ""
                },
                {
                    "name": "オムロン",
                    "code": "6645",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "デンソー",
                    "code": "6902",
                    "marketCap": 78000,
                    "url": ""
                },
                {
                    "name": "太陽誘電",
                    "code": "6976",
                    "marketCap": 4000,
                    "url": ""
                },
                {
                    "name": "OKI",
                    "code": "6703",
                    "marketCap": 1000,
                    "url": ""
                },
                {
                    "name": "明電舎",
                    "code": "6508",
                    "marketCap": 1000,
                    "url": ""
                },
                {
                    "name": "リコー",
                    "code": "7752",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "ニコン",
                    "code": "7731",
                    "marketCap": 5000,
                    "url": ""
                },
                {
                    "name": "シチズン時計",
                    "code": "7762",
                    "marketCap": 2500,
                    "url": ""
                },
                {
                    "name": "シャープ",
                    "code": "6753",
                    "marketCap": 5000,
                    "url": ""
                }
            ]
        },
        {
            "name": "消費財",
            "children": [
                {
                    "name": "ファーストリテイリング",
                    "code": "9983",
                    "marketCap": 140000,
                    "url": ""
                },
                {
                    "name": "トヨタ自動車",
                    "code": "7203",
                    "marketCap": 480000,
                    "url": ""
                },
                {
                    "name": "ホンダ",
                    "code": "7267",
                    "marketCap": 85000,
                    "url": ""
                },
                {
                    "name": "セブン&アイ",
                    "code": "3382",
                    "marketCap": 55000,
                    "url": ""
                },
                {
                    "name": "花王",
                    "code": "4452",
                    "marketCap": 25000,
                    "url": ""
                },
                {
                    "name": "JT",
                    "code": "2914",
                    "marketCap": 80000,
                    "url": ""
                },
                {
                    "name": "スズキ",
                    "code": "7269",
                    "marketCap": 35000,
                    "url": ""
                },
                {
                    "name": "SUBARU",
                    "code": "7270",
                    "marketCap": 22000,
                    "url": ""
                },
                {
                    "name": "日産自動車",
                    "code": "7201",
                    "marketCap": 20000,
                    "url": ""
                },
                {
                    "name": "いすゞ",
                    "code": "7202",
                    "marketCap": 15000,
                    "url": ""
                },
                {
                    "name": "三菱自動車",
                    "code": "7211",
                    "marketCap": 7000,
                    "url": ""
                },
                {
                    "name": "ヤマハ発動機",
                    "code": "7272",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "ヤマハ",
                    "code": "7951",
                    "marketCap": 6000,
                    "url": ""
                },
                {
                    "name": "任天堂",
                    "code": "7974",
                    "marketCap": 75000,
                    "url": ""
                },
                {
                    "name": "バンダイナムコ",
                    "code": "7832",
                    "marketCap": 20000,
                    "url": ""
                },
                {
                    "name": "アサヒグループHD",
                    "code": "2502",
                    "marketCap": 28000,
                    "url": ""
                },
                {
                    "name": "キリンHD",
                    "code": "2503",
                    "marketCap": 18000,
                    "url": ""
                },
                {
                    "name": "サッポロHD",
                    "code": "2501",
                    "marketCap": 4000,
                    "url": ""
                },
                {
                    "name": "キッコーマン",
                    "code": "2801",
                    "marketCap": 18000,
                    "url": ""
                },
                {
                    "name": "味の素",
                    "code": "2802",
                    "marketCap": 30000,
                    "url": ""
                },
                {
                    "name": "ニチレイ",
                    "code": "2871",
                    "marketCap": 5000,
                    "url": ""
                },
                {
                    "name": "日本ハム",
                    "code": "2282",
                    "marketCap": 5000,
                    "url": ""
                },
                {
                    "name": "日清製粉G",
                    "code": "2002",
                    "marketCap": 6000,
                    "url": ""
                },
                {
                    "name": "宝HD",
                    "code": "2531",
                    "marketCap": 3000,
                    "url": ""
                },
                {
                    "name": "資生堂",
                    "code": "4911",
                    "marketCap": 15000,
                    "url": ""
                },
                {
                    "name": "イオン",
                    "code": "8267",
                    "marketCap": 30000,
                    "url": ""
                },
                {
                    "name": "J.フロント",
                    "code": "3086",
                    "marketCap": 4000,
                    "url": ""
                },
                {
                    "name": "三越伊勢丹",
                    "code": "3099",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "高島屋",
                    "code": "8233",
                    "marketCap": 4000,
                    "url": ""
                },
                {
                    "name": "東宝",
                    "code": "9602",
                    "marketCap": 9000,
                    "url": ""
                },
                {
                    "name": "電通グループ",
                    "code": "4324",
                    "marketCap": 10000,
                    "url": ""
                },
                {
                    "name": "楽天グループ",
                    "code": "4755",
                    "marketCap": 20000,
                    "url": ""
                },
                {
                    "name": "エムスリー",
                    "code": "2413",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "オリエンタルランド",
                    "code": "4661",
                    "marketCap": 80000,
                    "url": ""
                },
                {
                    "name": "TOPPAN",
                    "code": "7911",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "大日本印刷",
                    "code": "7912",
                    "marketCap": 13000,
                    "url": ""
                }
            ]
        },
        {
            "name": "金融",
            "children": [
                {
                    "name": "三菱UFJ",
                    "code": "8306",
                    "marketCap": 180000,
                    "url": ""
                },
                {
                    "name": "三井住友FG",
                    "code": "8316",
                    "marketCap": 120000,
                    "url": ""
                },
                {
                    "name": "みずほFG",
                    "code": "8411",
                    "marketCap": 80000,
                    "url": ""
                },
                {
                    "name": "東京海上HD",
                    "code": "8766",
                    "marketCap": 110000,
                    "url": ""
                },
                {
                    "name": "MS&AD",
                    "code": "8725",
                    "marketCap": 40000,
                    "url": ""
                },
                {
                    "name": "SOMPO",
                    "code": "8630",
                    "marketCap": 35000,
                    "url": ""
                },
                {
                    "name": "野村HD",
                    "code": "8604",
                    "marketCap": 30000,
                    "url": ""
                },
                {
                    "name": "大和証券G",
                    "code": "8601",
                    "marketCap": 15000,
                    "url": ""
                },
                {
                    "name": "第一生命HD",
                    "code": "8750",
                    "marketCap": 35000,
                    "url": ""
                },
                {
                    "name": "T&D",
                    "code": "8795",
                    "marketCap": 15000,
                    "url": ""
                },
                {
                    "name": "コンコルディア",
                    "code": "7186",
                    "marketCap": 9000,
                    "url": ""
                },
                {
                    "name": "りそなHD",
                    "code": "8308",
                    "marketCap": 20000,
                    "url": ""
                },
                {
                    "name": "千葉銀行",
                    "code": "8331",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "静岡銀行",
                    "code": "8355",
                    "marketCap": 7000,
                    "url": ""
                },
                {
                    "name": "ふくおかFG",
                    "code": "8354",
                    "marketCap": 7000,
                    "url": ""
                },
                {
                    "name": "クレディセゾン",
                    "code": "8253",
                    "marketCap": 5000,
                    "url": ""
                },
                {
                    "name": "オリックス",
                    "code": "8591",
                    "marketCap": 40000,
                    "url": ""
                }
            ]
        },
        {
            "name": "医薬品",
            "children": [
                {
                    "name": "第一三共",
                    "code": "4568",
                    "marketCap": 90000,
                    "url": ""
                },
                {
                    "name": "武田薬品",
                    "code": "4502",
                    "marketCap": 65000,
                    "url": ""
                },
                {
                    "name": "中外製薬",
                    "code": "4519",
                    "marketCap": 95000,
                    "url": ""
                },
                {
                    "name": "アステラス製薬",
                    "code": "4503",
                    "marketCap": 30000,
                    "url": ""
                },
                {
                    "name": "エーザイ",
                    "code": "4523",
                    "marketCap": 15000,
                    "url": ""
                },
                {
                    "name": "塩野義製薬",
                    "code": "4507",
                    "marketCap": 20000,
                    "url": ""
                },
                {
                    "name": "住友ファーマ",
                    "code": "4506",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "大塚HD",
                    "code": "4578",
                    "marketCap": 30000,
                    "url": ""
                },
                {
                    "name": "協和キリン",
                    "code": "4151",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "テルモ",
                    "code": "4543",
                    "marketCap": 35000,
                    "url": ""
                }
            ]
        },
        {
            "name": "素材",
            "children": [
                {
                    "name": "信越化学",
                    "code": "4063",
                    "marketCap": 130000,
                    "url": ""
                },
                {
                    "name": "日本製鉄",
                    "code": "5401",
                    "marketCap": 35000,
                    "url": ""
                },
                {
                    "name": "JFE",
                    "code": "5411",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "神戸製鋼所",
                    "code": "5406",
                    "marketCap": 7000,
                    "url": ""
                },
                {
                    "name": "住友金属鉱山",
                    "code": "5713",
                    "marketCap": 18000,
                    "url": ""
                },
                {
                    "name": "DOWA",
                    "code": "5714",
                    "marketCap": 3000,
                    "url": ""
                },
                {
                    "name": "三菱マテリアル",
                    "code": "5711",
                    "marketCap": 3500,
                    "url": ""
                },
                {
                    "name": "三井金属",
                    "code": "5706",
                    "marketCap": 2500,
                    "url": ""
                },
                {
                    "name": "旭化成",
                    "code": "3407",
                    "marketCap": 14000,
                    "url": ""
                },
                {
                    "name": "三菱ケミカル",
                    "code": "4188",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "レゾナック",
                    "code": "4004",
                    "marketCap": 6000,
                    "url": ""
                },
                {
                    "name": "住友化学",
                    "code": "4005",
                    "marketCap": 5000,
                    "url": ""
                },
                {
                    "name": "日産化学",
                    "code": "4021",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "東ソー",
                    "code": "4042",
                    "marketCap": 6000,
                    "url": ""
                },
                {
                    "name": "三井化学",
                    "code": "4183",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "UBE",
                    "code": "4208",
                    "marketCap": 2500,
                    "url": ""
                },
                {
                    "name": "デンカ",
                    "code": "4061",
                    "marketCap": 2500,
                    "url": ""
                },
                {
                    "name": "イビデン",
                    "code": "4062",
                    "marketCap": 9000,
                    "url": ""
                },
                {
                    "name": "日本化薬",
                    "code": "4272",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "太平洋セメント",
                    "code": "5233",
                    "marketCap": 4000,
                    "url": ""
                },
                {
                    "name": "AGC",
                    "code": "5201",
                    "marketCap": 11000,
                    "url": ""
                },
                {
                    "name": "日本ガイシ",
                    "code": "5333",
                    "marketCap": 5000,
                    "url": ""
                },
                {
                    "name": "TOTO",
                    "code": "5332",
                    "marketCap": 7000,
                    "url": ""
                },
                {
                    "name": "東洋紡",
                    "code": "3101",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "帝人",
                    "code": "3401",
                    "marketCap": 2500,
                    "url": ""
                },
                {
                    "name": "東レ",
                    "code": "3402",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "クラレ",
                    "code": "3405",
                    "marketCap": 5000,
                    "url": ""
                }
            ]
        },
        {
            "name": "資本財・その他",
            "children": [
                {
                    "name": "コマツ",
                    "code": "6301",
                    "marketCap": 40000,
                    "url": ""
                },
                {
                    "name": "クボタ",
                    "code": "6326",
                    "marketCap": 25000,
                    "url": ""
                },
                {
                    "name": "ダイキン工業",
                    "code": "6367",
                    "marketCap": 65000,
                    "url": ""
                },
                {
                    "name": "荏原製作所",
                    "code": "6361",
                    "marketCap": 10000,
                    "url": ""
                },
                {
                    "name": "三菱重工",
                    "code": "7011",
                    "marketCap": 60000,
                    "url": ""
                },
                {
                    "name": "IHI",
                    "code": "7013",
                    "marketCap": 20000,
                    "url": ""
                },
                {
                    "name": "川崎重工",
                    "code": "7012",
                    "marketCap": 10000,
                    "url": ""
                },
                {
                    "name": "リクルートHD",
                    "code": "6098",
                    "marketCap": 100000,
                    "url": ""
                },
                {
                    "name": "三菱商事",
                    "code": "8058",
                    "marketCap": 130000,
                    "url": ""
                },
                {
                    "name": "伊藤忠商事",
                    "code": "8001",
                    "marketCap": 100000,
                    "url": ""
                },
                {
                    "name": "三井物産",
                    "code": "8031",
                    "marketCap": 90000,
                    "url": ""
                },
                {
                    "name": "丸紅",
                    "code": "8002",
                    "marketCap": 45000,
                    "url": ""
                },
                {
                    "name": "住友商事",
                    "code": "8053",
                    "marketCap": 40000,
                    "url": ""
                },
                {
                    "name": "双日",
                    "code": "2768",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "豊田通商",
                    "code": "8015",
                    "marketCap": 30000,
                    "url": ""
                },
                {
                    "name": "日立建機",
                    "code": "6305",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "住友重機械",
                    "code": "6302",
                    "marketCap": 4000,
                    "url": ""
                },
                {
                    "name": "日本製鋼所",
                    "code": "5631",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "日立造船",
                    "code": "7004",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "日本精工",
                    "code": "6471",
                    "marketCap": 4000,
                    "url": ""
                },
                {
                    "name": "NTN",
                    "code": "6472",
                    "marketCap": 1500,
                    "url": ""
                },
                {
                    "name": "ジェイテクト",
                    "code": "6473",
                    "marketCap": 4000,
                    "url": ""
                },
                {
                    "name": "オークマ",
                    "code": "6103",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "アマダ",
                    "code": "6113",
                    "marketCap": 5000,
                    "url": ""
                },
                {
                    "name": "SMC",
                    "code": "6273",
                    "marketCap": 50000,
                    "url": ""
                }
            ]
        },
        {
            "name": "インフラ・不動産",
            "children": [
                {
                    "name": "NTT",
                    "code": "9432",
                    "marketCap": 150000,
                    "url": ""
                },
                {
                    "name": "KDDI",
                    "code": "9433",
                    "marketCap": 100000,
                    "url": ""
                },
                {
                    "name": "ソフトバンク",
                    "code": "9434",
                    "marketCap": 85000,
                    "url": ""
                },
                {
                    "name": "JR東日本",
                    "code": "9020",
                    "marketCap": 30000,
                    "url": ""
                },
                {
                    "name": "JR西日本",
                    "code": "9021",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "JR東海",
                    "code": "9022",
                    "marketCap": 35000,
                    "url": ""
                },
                {
                    "name": "東急",
                    "code": "9005",
                    "marketCap": 10000,
                    "url": ""
                },
                {
                    "name": "小田急",
                    "code": "9007",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "京王",
                    "code": "9008",
                    "marketCap": 6000,
                    "url": ""
                },
                {
                    "name": "京成",
                    "code": "9009",
                    "marketCap": 6000,
                    "url": ""
                },
                {
                    "name": "東武",
                    "code": "9001",
                    "marketCap": 7000,
                    "url": ""
                },
                {
                    "name": "ヤマトHD",
                    "code": "9064",
                    "marketCap": 8000,
                    "url": ""
                },
                {
                    "name": "日本郵船",
                    "code": "9101",
                    "marketCap": 25000,
                    "url": ""
                },
                {
                    "name": "商船三井",
                    "code": "9104",
                    "marketCap": 20000,
                    "url": ""
                },
                {
                    "name": "川崎汽船",
                    "code": "9107",
                    "marketCap": 15000,
                    "url": ""
                },
                {
                    "name": "日本航空",
                    "code": "9201",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "ANA HD",
                    "code": "9202",
                    "marketCap": 14000,
                    "url": ""
                },
                {
                    "name": "三菱倉庫",
                    "code": "9301",
                    "marketCap": 4000,
                    "url": ""
                },
                {
                    "name": "東京電力HD",
                    "code": "9501",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "中部電力",
                    "code": "9502",
                    "marketCap": 14000,
                    "url": ""
                },
                {
                    "name": "関西電力",
                    "code": "9503",
                    "marketCap": 18000,
                    "url": ""
                },
                {
                    "name": "東京ガス",
                    "code": "9531",
                    "marketCap": 15000,
                    "url": ""
                },
                {
                    "name": "大阪ガス",
                    "code": "9532",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "三井不動産",
                    "code": "8801",
                    "marketCap": 35000,
                    "url": ""
                },
                {
                    "name": "三菱地所",
                    "code": "8802",
                    "marketCap": 30000,
                    "url": ""
                },
                {
                    "name": "住友不動産",
                    "code": "8830",
                    "marketCap": 22000,
                    "url": ""
                },
                {
                    "name": "東京建物",
                    "code": "8804",
                    "marketCap": 5000,
                    "url": ""
                },
                {
                    "name": "大和ハウス",
                    "code": "1925",
                    "marketCap": 28000,
                    "url": ""
                },
                {
                    "name": "積水ハウス",
                    "code": "1928",
                    "marketCap": 22000,
                    "url": ""
                },
                {
                    "name": "大成建設",
                    "code": "1801",
                    "marketCap": 10000,
                    "url": ""
                },
                {
                    "name": "大林組",
                    "code": "1802",
                    "marketCap": 10000,
                    "url": ""
                },
                {
                    "name": "清水建設",
                    "code": "1803",
                    "marketCap": 7000,
                    "url": ""
                },
                {
                    "name": "鹿島",
                    "code": "1812",
                    "marketCap": 12000,
                    "url": ""
                }
            ]
        },
        {
            "name": "エネルギー",
            "children": [
                {
                    "name": "ENEOS",
                    "code": "5020",
                    "marketCap": 22000,
                    "url": ""
                },
                {
                    "name": "出光興産",
                    "code": "5019",
                    "marketCap": 12000,
                    "url": ""
                },
                {
                    "name": "INPEX",
                    "code": "1605",
                    "marketCap": 25000,
                    "url": ""
                }
            ]
        },
        {
            "name": "その他",
            "children": [
                {
                    "name": "その他 1",
                    "code": "9900",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 2",
                    "code": "9901",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 3",
                    "code": "9902",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 4",
                    "code": "9903",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 5",
                    "code": "9904",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 6",
                    "code": "9905",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 7",
                    "code": "9906",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 8",
                    "code": "9907",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 9",
                    "code": "9908",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 10",
                    "code": "9909",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 11",
                    "code": "9910",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 12",
                    "code": "9911",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 13",
                    "code": "9912",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 14",
                    "code": "9913",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 15",
                    "code": "9914",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 16",
                    "code": "9915",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 17",
                    "code": "9916",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 18",
                    "code": "9917",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 19",
                    "code": "9918",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 20",
                    "code": "9919",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 21",
                    "code": "9920",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 22",
                    "code": "9921",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 23",
                    "code": "9922",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 24",
                    "code": "9923",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 25",
                    "code": "9924",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 26",
                    "code": "9925",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 27",
                    "code": "9926",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 28",
                    "code": "9927",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 29",
                    "code": "9928",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 30",
                    "code": "9929",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 31",
                    "code": "9930",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 32",
                    "code": "9931",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 33",
                    "code": "9932",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 34",
                    "code": "9933",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 35",
                    "code": "9934",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 36",
                    "code": "9935",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 37",
                    "code": "9936",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 38",
                    "code": "9937",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 39",
                    "code": "9938",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 40",
                    "code": "9939",
                    "marketCap": 2000,
                    "url": ""
                },
                {
                    "name": "その他 41",
                    "code": "9940",
                    "marketCap": 2000,
                    "url": ""
                }
            ]
        }
    ]
};

// YouTube Video Links (Code: URL)
// Add your analysis videos here
// NOTE: You can also strictly add "url": "..." in the marketData structure above,
// but this map is kept for backward compatibility and ease of use.
const videoLinks = {
    // "7203": "https://youtu.be/...",
};
